version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'
